### PR TITLE
Fix params for new workflow methods

### LINKED ISSUE #42: Wrong params and TypeHints for new workflow methods
export() should accept integers only as workflowId parameter.
createConfigured() params do not match the evalanche configuration.

### PR DESCRIPTION
**Pull request by simonduerr**
Methods export and createConfigured have wrong params or type hints.
Fixes #42.

### CODE REVIEW

File: tests/Client/Workflow/WorkflowClientTest.php [hunk 1]
```diff
@@ -168,34 +168,43 @@ public function testPushProfilesIntoCampaignCanReturnBoolean()
 
     public function testCreateConfiguredReturnsInt()
```
Comment (WorksDev) [inline tests/Client/Workflow/WorkflowClientTest.php]: returns no int anymore

Comment (usox) [reply tests/Client/Workflow/WorkflowClientTest.php]: I've edited the file
