### PR TITLE
Fix wrong parameter typehint for profileclient

### LINKED ISSUE #151: Fetching a profile using the encrypted UID
Hi,

I currently fail to fetch profiles using the encrypted UID.

The help center describes the UID in this document
https://help.evalanche.cloud/hc/en-us/articles/360026462232-SOAP-API-Overview
to be mapped to the virtual attribute "SID".
Which is true as I can fetch this attribute when reading out profiles.

But: I can not use getByKey() from the ProfileClient because it throws an exception:
Unknown pool attribute: SID

An other possible way could be using getById instead:

The help center describing getById of the ProfileClient
https://help.evalanche.cloud/hc/en-us/articles/360042265151-SOAP-Profile
says:
string profile_id: ID or UID of the profile to be searched

BUT: That is not possible using this api connector because of the paramater is specified as int:
https://github.com/SC-Networks/evalanche-soap-api-connector/blob/aa7a43369bea188eaafb3aa7dcbce60b7176fe50/src/Client/Profile/ProfileClient.php#L154
so that the UID can not be passed.

Could either getByKey or getById be fixed so that I can use the UID?

Thanks.

### PR DESCRIPTION
**Pull request by WorksDev**
- fixes #151

### CODE REVIEW

File: src/Client/Profile/ProfileClient.php [hunk 1]
```diff
@@ -151,7 +151,7 @@ public function getBounces(int $id, array $poolAttributeList, int $timestampStar
      * @return HashMapInterface
      * @throws EmptyResultException
      */
-    public function getById(int $id): HashMapInterface
+    public function getById(string $id): HashMapInterface
```
Comment (usox) [inline src/Client/Profile/ProfileClient.php:154]: I'd say, this breaks BC, doesn't it? Maybe we need to drop the typehint until the next major version and add a union typehint `int|strig`.

**Review by usox — CHANGES_REQUESTED** [review]

File: src/Client/Profile/ProfileClient.php (hunk 1 above)
Comment (WorksDev) [reply src/Client/Profile/ProfileClient.php:154]: It's a BC, it was just a quick Shot 
. In fact, I would tend to establish a completely new method getBySid(String $sid). Seems to me to be the best solution in general

Comment (usox) [reply src/Client/Profile/ProfileClient.php:154]: > . In fact, I would tend to establish a completely new method getBySid(String $sid). Seems to me to be the best solution in general

I second that.

**Review by usox — APPROVED** [review]
